// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwaddleGram.Data;

namespace TwaddleGram.Migrations
{
    [DbContext(typeof(TwaddleDbContext))]
    [Migration("20190218224005_new-seed-data")]
    partial class newseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TwaddleGram.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<int>("PostID");

                    b.HasKey("ID");

                    b.HasIndex("PostID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "They're great for swollen toes!",
                            PostID = 1
                        },
                        new
                        {
                            ID = 2,
                            Content = "Ewww... I don't wanna smell your feet.",
                            PostID = 1
                        },
                        new
                        {
                            ID = 3,
                            Content = "You could wear them for a pedicure!",
                            PostID = 1
                        },
                        new
                        {
                            ID = 4,
                            Content = "Quite possibly the most disgusting thing ever.",
                            PostID = 11
                        },
                        new
                        {
                            ID = 5,
                            Content = "Gotta teach them early!",
                            PostID = 13
                        });
                });

            modelBuilder.Entity("TwaddleGram.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption");

                    b.Property<string>("Photo");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Caption = "These boots are rockin'.",
                            Photo = "https://twaddlegram.blob.core.windows.net/userpics/boots.jpg",
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Caption = "Duckdog!",
                            Photo = "https://twaddlegram.blob.core.windows.net/userpics/dog-duck.jpg",
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            Caption = "mmm....delish!",
                            Photo = "https://twaddlegram.blob.core.windows.net/userpics/bubblegum.jpg",
                            UserID = 3
                        },
                        new
                        {
                            ID = 4,
                            Caption = "grrrr!",
                            Photo = "https://twaddlegram.blob.core.windows.net/userpics/cthulhu.jpg",
                            UserID = 4
                        },
                        new
                        {
                            ID = 5,
                            Caption = "This child has a future in the domestic arts.",
                            Photo = "https://twaddlegram.blob.core.windows.net/userpics/sweep.png",
                            UserID = 5
                        });
                });

            modelBuilder.Entity("TwaddleGram.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Username = "gwen"
                        },
                        new
                        {
                            ID = 2,
                            Username = "dave"
                        },
                        new
                        {
                            ID = 3,
                            Username = "brandon"
                        },
                        new
                        {
                            ID = 4,
                            Username = "alyssa"
                        },
                        new
                        {
                            ID = 5,
                            Username = "madi"
                        });
                });

            modelBuilder.Entity("TwaddleGram.Models.Comment", b =>
                {
                    b.HasOne("TwaddleGram.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TwaddleGram.Models.Post", b =>
                {
                    b.HasOne("TwaddleGram.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
