// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwaddleGram.Data;

namespace TwaddleGram.Migrations
{
    [DbContext(typeof(TwaddleDbContext))]
    [Migration("20190213214625_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TwaddleGram.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<int>("PostID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("PostID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "first comment",
                            PostID = 1
                        },
                        new
                        {
                            ID = 2,
                            Content = "second comment",
                            PostID = 1
                        },
                        new
                        {
                            ID = 3,
                            Content = "third comment",
                            PostID = 1
                        },
                        new
                        {
                            ID = 4,
                            Content = "fourth comment",
                            PostID = 1
                        },
                        new
                        {
                            ID = 5,
                            Content = "fifth comment",
                            PostID = 1
                        });
                });

            modelBuilder.Entity("TwaddleGram.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption");

                    b.Property<int>("Photo");

                    b.Property<int>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Caption = "first post",
                            Photo = 0,
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            Caption = "second post",
                            Photo = 0,
                            UserID = 1
                        },
                        new
                        {
                            ID = 3,
                            Caption = "third post",
                            Photo = 0,
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            Caption = "fourth post",
                            Photo = 0,
                            UserID = 1
                        },
                        new
                        {
                            ID = 5,
                            Caption = "fifth post",
                            Photo = 0,
                            UserID = 1
                        });
                });

            modelBuilder.Entity("TwaddleGram.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Avatar");

                    b.Property<string>("Username");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Avatar = 0,
                            Username = "gwen"
                        },
                        new
                        {
                            ID = 2,
                            Avatar = 0,
                            Username = "dave"
                        },
                        new
                        {
                            ID = 3,
                            Avatar = 0,
                            Username = "brandon"
                        },
                        new
                        {
                            ID = 4,
                            Avatar = 0,
                            Username = "alyssa"
                        },
                        new
                        {
                            ID = 5,
                            Avatar = 0,
                            Username = "madi"
                        });
                });

            modelBuilder.Entity("TwaddleGram.Models.Comment", b =>
                {
                    b.HasOne("TwaddleGram.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TwaddleGram.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("TwaddleGram.Models.Post", b =>
                {
                    b.HasOne("TwaddleGram.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
